### ISSUE TITLE
impossible seed

### ISSUE THREAD

**Issue by KrakenTheJaken** [adrienntindall/hgss-map-randomizer#10]
I was playing through seed and eventually gave up. I was looking where key locations were and the burnt tower lower part (ignoring hallways) was connected to 2 other loading zones. One was a gym and the other was some random house, meaning it was impossible to get to.  I've attached the log, and a video showing   the issue  (also im using version 1.2.4)
https://www.youtube.com/watch?v=gaeVei6FFA8
[Pokemon - SoulSilver Version (USA).nds_map_randomized.log](https://github.com/adrienntindall/hgss-map-randomizer/files/8735121/Pokemon.-.SoulSilver.Version.USA.nds_map_randomized.log)

**Comment by adrienntindall** [comment]
mm yup, looks like I swapped the labels on the N and S side of the union cave paths to alph. Should be fixed and good for the next update
