### ISSUE TITLE
impossible seed.

### ISSUE THREAD

**Issue by KrakenTheJaken** [adrienntindall/hgss-map-randomizer#13]
I was playing through a seed, but eventually gave up on finding will. Looking through the logs, I believe this seed was impossible. The only way to access will was through the E4 3-way area, and the only way to get into that was from the whirl islands ladder (near the staircase). But there's a guy blocking it. To get him to not block it you need the silver wing, but the final area (observation deck), where you get the wing is only accessible via rock climb. here is the video link to show it

link: https://youtu.be/ZS3m_x8lbgQ

[Pokemon - SoulSilver Version (USA).nds_map_randomized.log](https://github.com/adrienntindall/hgss-map-randomizer/files/8790405/Pokemon.-.SoulSilver.Version.USA.nds_map_randomized.log)

**Comment by adrienntindall** [comment]
Few questions if that is alright:
1) Did you accidentally put the soul silver rom in the /heartgold_rom folder? If so, that would be the issue
2) What version of the randomizer were you using? If you don't remember, when did you download it?

**Comment by adrienntindall** [comment]
Regardless, I did find an issue with labeling the Silver Wing as the Rainbow Wing in the SS logic, my mistake on there, and huge apologies for causing the impossible seed. This will be addressed in the next update

**Comment by KrakenTheJaken** [comment]
I did put it in the soul silver folder, and it should be the most recent
