### ISSUE TITLE
impossible seed

### ISSUE THREAD

**Issue by KrakenTheJaken** [adrienntindall/hgss-map-randomizer#14]
In this seed, the burnt tower was locked behind surf.

[base.nds_map_randomized.log](https://github.com/adrienntindall/hgss-map-randomizer/files/8794395/base.nds_map_randomized.log)

https://user-images.githubusercontent.com/58538619/170893763-e2442945-0444-4bd1-85a6-0e83fac7e719.mp4

**Comment by adrienntindall** [comment]
It looks like the labels for those ladders in whirl islands were swapped, so the logic thought the burnt tower was on the left and not the right, which would've made this seed completely possible. Huge apologies for the bug and thanks for bringing it to my attention, it has been fixed and will be pushed in the next update.
