### ISSUE TITLE
impossible seed (maybe)

### ISSUE THREAD

**Issue by KrakenTheJaken** [adrienntindall/hgss-map-randomizer#18]
I may have come across another seed. While playing I eventually gave up trying to find sprout tower. Looking through the logs sprout tower is connected to a 3-way, the other way leads to the souvenir shop area (under the closet), I'm fairly certain that this doesn't open until you've gotten surf but if theirs another trigger then I'm mistaken., though the entrance is accessible, so it may be an error on my part.

The other exit leads just to dead ends.

a video because I'm bad at explaining + logs :)

https://user-images.githubusercontent.com/58538619/171749378-7030d2fe-8ecd-4b1c-9cc9-691479c056df.mp4

[base.nds_map_randomized.nds_map_randomized.log](https://github.com/adrienntindall/hgss-map-randomizer/files/8828198/base.nds_map_randomized.nds_map_randomized.log)

**Comment by adrienntindall** [comment]
Based on the log file generated... you didn't happen to randomize an already randomized rom did you? cause that would 1000% mess with the logic

**Comment by KrakenTheJaken** [comment]
the log file name was me just re-naming. The rom I put into the soul-silver folder is not randomized. (its how I found sprout tower)
