### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by Malachi4242** [adrienntindall/hgss-map-randomizer#24]
Hi there! 

I've tried unzipping and extracting the zip files a few times now and yet I still can't seem to get "\heartgold_rom or \soulsilver_rom folders" as well as the randomized rom folder, I've tried downloading the release version too yet it still doesn't show the files, is there a reason for this?

**Comment by adrienntindall** [comment]
https://github.com/adrienntindall/hgss-map-randomizer/releases/tag/Release
Go here and download "hgss-map-randomizer-1.3.zip"
I can confirm the files are there
If you don't see them, then I have no idea what's up, maybe it has to do with how your machine unarchives .zip files
If that is the case, just make sure to create those folders instead
