### ISSUE TITLE
Softlock / game freeze while in caves

### ISSUE THREAD

**Issue by Pokken1** [adrienntindall/hgss-map-randomizer#26]
Hi, I've been playing the randomizer for about 4 hours and I am really enjoying it, good work on that. I realized everytime I got into a cave and tried to go back/use stairs to go to a random warp, the game just freezes. The only way to avoid it is loading a previous savestate and not going there again. Is it just me or it's a common bug? Maybe I will have to restart the run and use a different seed. Thank you beforehand

**Comment by Pokken1** [comment]
> 

playing heartgold and spanish version.

**Comment by adrienntindall** [comment]
download 1.3.1, it addresses the issue
