### ISSUE TITLE
Error: Unbeatable seed. Retrying...

### ISSUE THREAD

**Issue by wurtz2208** [adrienntindall/hgss-map-randomizer#28]
This is the information i get when i try to randomize my rom - what is the solution? I'm EU based and using a rom correponding to that

**Comment by adrienntindall** [comment]
Leave it be, HGSS has a ton of locks and keys and as a result a ton of unbeatable seeds. It usually takes a minute or two to find a good seed, if it goes any longer it might be in an infinite loop- which usually means you dragged a newer version's folder into an older versions folder (don't do that).
