### ISSUE TITLE
Impossible seed due to lack of access to Cut

### ISSUE THREAD

**Issue by Twengdi** [adrienntindall/hgss-map-randomizer#29]
Erika's gym puzzle requires you to use Cut in order to get to her. Cut can only be learned through the HM, which is obtained after doing the Farfetch'd thing in Ilex Forest. The Farfetch'd thing is only triggered after doing the rival fight in Azalea Town. This rival fight is only triggered after beating the Rockets in Slowpoke Well. The only way to access the part of Slowpoke Well with the Rockets is through Mahogany Town -> Route 43 Gate interior (the one with the Rockets who take your money). However, this leads to the left side of the Well. Normally, you would use Strength to push the boulder and get back to the right side, but Proton is actually physically blocking the boulder, preventing you from fighting him. According to the log, the right side of this part of Slowpoke Well leads to a dead end inside a house, meaning that there is no physical way to fight Proton, and therefore no way to activate the long sequence of events that leads to you getting Cut. I tried pushing the boulder, saving, and reloading the game in hopes that the boulder would reset to its original position and essentially "teleport" behind me, but it ended up staying where I pushed it.
[HeartGold Random Map 1.log](https://github.com/adrienntindall/hgss-map-randomizer/files/8885432/HeartGold.Random.Map.1.log)

**Comment by adrienntindall** [comment]
Which version of the randomizer were you using, 1.3 had this issue but it should've been fixed in 1.3.1
If this is not the case, please let me know immediately
