### ISSUE TITLE
Non-US Roms can not be loaded in Emulator after Randomization

### ISSUE THREAD

**Issue by CodeTappert** [adrienntindall/hgss-map-randomizer#3]
As mentioned in the title there is a problem with Non-US Versions of Roms.

The randomization seems to work but it wont load in several emulators. 

Then i tested it with a US-Rom and it loaded instantly.

**Comment by adrienntindall** [comment]
I'm not too familiar with foreign-language ROMs, but if I were to guess it would likely be because the arm9 binary is different in different translations (it's even pretty different between versions!) Deleting that and accepting the copy error might be fine enough to fix it, but then it would lead to a buncha animation issues that make it very very difficult to progress.

I'd like to look into it more to make the mod more accessible, do you think you can tell me what non-US rom you're trying to randomize so I can pick it apart and analyze it a bit more?

**Comment by CodeTappert** [comment]
I tried the german version of the game.
"Pokemon - Goldene Edition HeartGold (Germany).nds"

If you need help with any translation/language problems let me know! I am happy to help

**Comment by CodeTappert** [comment]
Hello,
i tried it again with the newly released version. At least the game starts now. But the first warp (down the stairs from the room) always goes to a blackscreen while music still plays.

Here is what was in the command line during randomization:
```
Reading in warps!
Warning: PLAYER_HOUSE_TOP_ENT doesn't have a valid original
WARNING: PLAYER_HOUSE_TOP_EXIT is missing a definition for PLAYER_HOUSE_TOP_ENT
Done reading!
Getting Blocks!
Blocks gotten!
Starting Randomization!
Randomized!
Setting Warps!
Warps Set!
Pokemon - Goldene Edition HeartGold (Germany).nds_map_randomized.nds
Nintendo DS rom tool 1.31 - Aug  8 2006 07:57:02 by Rafael Vuijk (aka DarkFader)
```

Attached is the log file that was created during randomizatio
[Pokemon - Goldene Edition HeartGold (Germany).nds_map_randomized.log](https://github.com/adrienntindall/hgss-map-randomizer/files/8693638/Pokemon.-.Goldene.Edition.HeartGold.Germany.nds_map_randomized.log)
n

**Comment by adrienntindall** [comment]
Yeah, the issue hasn't been resolved yet, it's a problem with some of the changed scripts being at completely different offsets in the German version. I can push a version in a few hours that will let the rom start and let you play, though I can't guarantee it'll have all the QoL stuff I added in (mostly teleport and fly being able to be used anywhere). WIll reply again once it is ready, and thank you for reminding me!

**Comment by adrienntindall** [comment]
Looks like I've been encountering more issues than expected getting the German version to load properly with all the changes intact, apologies if it takes a bit longer

**Comment by adrienntindall** [comment]
Quick update: I was able to make and edit the scripts properly for the German version, but there's something weird with the way NDStool does compression, so rebuilding the rom with the new scripts (or even just a decompressed version of the original scripts) is what causes the game to fail to boot. 
If you know anyone who does NDS rom hacking for German games and could help me out, that'd be great, but till then I'll be trying to look for a workaround for this issue.

**Comment by CodeTappert** [comment]
I really dont know anyone who only works on german roms. But the pokemon randomizer (https://github.com/Ajarmar/universal-pokemon-randomizer-zx) fully supports most lanugages.

**Comment by adrienntindall** [comment]
Thank you for being patient, German roms work now =)
It'll auto-detect the language so you can just use the latest version as you would with an English rom
