### ISSUE TITLE
Can't access Sprout Tower top floor to unlock Falkner fight

### ISSUE THREAD

**Issue by Twengdi** [adrienntindall/hgss-map-randomizer#37]
After checking with DSPRE, it seems that the top floor of Sprout Tower is located inside the gate leading to Victory Road. Two of the other doors inside that gate lead to dead-ends, while the last door connects to the Ruins of Alph door that requires Ho-Oh to unlock. Even if you were to somehow complete all the conditions for unlocking Ho-Oh, the top of Bell Tower where you can catch Ho-Oh is located in a Whirl Islands entrance behind a Whirlpool. Weirdly enough, the log claims that this gate actually leads to the Ruins of Alph door that requires the Water Stone, when the actual Water Stone room is accessed from Fuchsia Gym's entrance and leads to a dead-end. There might be an issue with the labeling of the Ruins of Alph rooms, as the log seems to have it so that Puzzle Room 3 = Water Stone Room and Puzzle Room 4 = Ho-Oh Room, when it should be the other way around (Puzzle Room 3 = Ho-Oh Room and Puzzle Room 4 = Water Stone Room).

**Comment by adrienntindall** [comment]
Can you send me the logs? The alph rooms were added last so they definitely have the least amount of testing so I wouldn't doubt they'd be mislabeled.

**Comment by Twengdi** [comment]
Here is the log file:
[HeartGold Random Map 2.log](https://github.com/adrienntindall/hgss-map-randomizer/files/8954526/HeartGold.Random.Map.2.log)
