### ISSUE TITLE
Randomized ROM not appearing in folder (v. 1.3.2)

### ISSUE THREAD

**Issue by True-Iron** [adrienntindall/hgss-map-randomizer#40]
After running the randomizer for HG, I can see the randomized log in the randomized_roms folder, but not the ROM file. I attempted this multiple times, and with multiple versions of the HG ROM, and the issue persists on version 1.3.2. The original non-randomized ROM runs without any issues on my emulator.

Attached are two of the logs produced, for reference.

[4780 - Pokemon HeartGold (U)(Xenophobia).nds_map_randomized.log](https://github.com/adrienntindall/hgss-map-randomizer/files/8994061/4780.-.Pokemon.HeartGold.U.Xenophobia.nds_map_randomized.log)
[Pokemon - HeartGold Version (USA).nds_map_randomized.log](https://github.com/adrienntindall/hgss-map-randomizer/files/8994062/Pokemon.-.HeartGold.Version.USA.nds_map_randomized.log)

**Comment by True-Iron** [comment]
I further tested with version 1.3.1 and version 1.3, and both led to the same error

**Comment by adrienntindall** [comment]
Gonna need the information provided, otherwise Im going to close this issue since it doesn't seem to be an issue for anyone else

**Comment by zlloyd97** [comment]
I had a similar problem and used the command line to get a screenshot. The only thing available was the log file in the randomized_roms folder
![Screenshot (249)](https://user-images.githubusercontent.com/89108974/177599606-0e12b639-7df4-4ea9-83ea-a944f0b8216f.png)

**Comment by zlloyd97** [comment]
Thank you! v1.4.2 works.
