### ISSUE TITLE
Dual-bound warp `VIOLET_GATE_E_INT_R31`

### ISSUE THREAD

**Issue by qoala** [adrienntindall/hgss-map-randomizer#44]
Got confused when I found a second way to Blaine's gym. Pulled up the log and found that there's 3 lines with `VIOLET_GATE_E_INT_R31`; it's linked to both `MT_MOON_LADDER_DOWN_N` and `BELL_TOWER_F4_LADDER_UP_NW`

Version: compiled the randomizer myself at 6590c8a (I wanted the dragon's den fix after also encountering that issue on a previous run).

log: [pokehg.nds_map_randomizer.20220702.log](https://github.com/adrienntindall/hgss-map-randomizer/files/9033908/pokehg.nds_map_randomizer.20220702.log)

**Comment by adrienntindall** [comment]
_sigh_ I thought this was fixed but it clearly isn't
basically, some warps will be like that very rarely, but as far as I can tell the logic accounts for the 2->1 warps so the seed should be possible to complete. there's nothing unusual/special about the warps it affects in particular, and Im 80% sure this happens during the main progression check. I'll continue to look into it and see if I can fix it, but whenever Im generating seeds of my own it only happens maybe <10% of the time, so debugging it has been difficult.

**Comment by qoala** [comment]
Hmm... for a moment I thought I might have the seed that generated this run, but I don't. Maybe the seed should be added to the log file. Could help reproduce things.

**Comment by adrienntindall** [comment]
Yeah I just added that earlier tonight, seed thing is still in partial-development so no need to make issues bout it till it's actually released

**Comment by adrienntindall** [comment]
Was able to find a bugged seed after a while and managed to pinpoint the issue now that I can step through the randomization process of said bugged seed. The issue ended up being with a function that gets used to set _maybe_ 5-10 warp pairs per seed, which explains why it was happening so infrequently.
