### ISSUE TITLE
HGSS ROM not outputting?

### ISSUE THREAD

**Issue by Twengdi** [adrienntindall/hgss-map-randomizer#46]
I tried to randomize HGSS but I'm not getting a ROM output, only a log file. This happens for both HeartGold and SoulSilver.
![Screenshot 2022-07-05 232110](https://user-images.githubusercontent.com/55635343/177461056-b109faa4-6f24-4566-b5ff-02fa99970de7.png)

**Comment by adrienntindall** [comment]
Do you have the command line output? When this happens I _think_ it's an issue with NDStool, but if it was working before I have no clue why it'd suddenly not work

**Comment by Twengdi** [comment]
![Screenshot (70)](https://user-images.githubusercontent.com/55635343/177464050-aab27d49-2bb4-4b47-b469-cf05d6b1abd0.png)
The window closes automatically shortly after this shows up. I don't recall this window closing automatically before. Doesn't it usually have a line that says like "press any key to finish"?

**Comment by adrienntindall** [comment]
Yeah it does, if anything I'd say use 1.4 while I work out this issue since I have confirmed that one is stable. I'll use the seed in that last line to test with, tysm for that.

**Comment by adrienntindall** [comment]
Found the issue - some White 2 overwrite data snuck its way into the overwrite data, and since the formats are different the program died trying to set warps in it. This also explains why Nimbasa City didn't have the changes I wanted, apologies for that, will make a commit ASAP
