### ISSUE TITLE
Clair locked behind Snorlax/Pokeflute

### ISSUE THREAD

**Issue by Twengdi** [adrienntindall/hgss-map-randomizer#47]
Clair is behind the Diglett Tunnel entrance blocked by Snorlax. According to the log file, to get the Pokeflute to remove Snorlax, I have to go to a door in Whirl Islands (on the slope past the guy who wants to see the Silver Wing). I've been to this door before, but it actually leads to the interior of the Lavender Town name rater.
[HeartGold Random Map 1.log](https://github.com/adrienntindall/hgss-map-randomizer/files/9068103/HeartGold.Random.Map.1.log)

**Comment by adrienntindall** [comment]
yup, looks like the labels were swapped in the radio tower and name rater buildings, my bad on that end. Unfortunately this does mean that the logic thinks that you get the flute in the name rater building... I'll fix it and push the patch with the correct labels in about an hour. The correct house should be 7, but looks like it wasn't in this seed, so you'd have to use wtw to beat this seed.
