### ISSUE TITLE
Victory road cliffside SW puts you behind a TV in a random house

### ISSUE THREAD

**Issue by bsqrdminus4ac** [adrienntindall/hgss-map-randomizer#49]
The SW exit on the Victory Road Cliffside takes me to inside a TV in a random house on route 4.  The house stairs take me to the normal downstairs of that house, but going up those stairs again puts me in Twist Mountain.  I also found the location that was supposed to randomize to Victory Road Cliffside SW (Twist 2F exit S), and it correctly takes me to the cliffside.

This was randomized using release 1.4.2.

[Attached log](https://github.com/adrienntindall/hgss-map-randomizer/files/9077826/W2.bug.log.log)

**Comment by adrienntindall** [comment]
Looks like that warp got corrupted when I was removing the Zoroark, thanks for bringing it to my attention
