### ISSUE TITLE
White 2 Fly HM Inaccessible

### ISSUE THREAD

**Issue by bsqrdminus4ac** [adrienntindall/hgss-map-randomizer#51]
Is it intentional that HM Fly can be inaccessible for certain seeds?  In my current seed, the Routre 5 east exit and trailer both lead to dead ends.  The west exit connects somewhere, but you cannot cross the line of npcs until you speak to the biker, who is only accessible from the east side.

**Comment by adrienntindall** [comment]
Since Fly isn't strictly necessary to beat the game, the logic does allow for scenarios like this (technically this is also true in HGSS, though the odds are much lower due to the number of connections to Cianwood).
