### ISSUE TITLE
Funny W2 loop

### ISSUE THREAD

**Issue by bsqrdminus4ac** [adrienntindall/hgss-map-randomizer#52]
Got the following randomization, leading to a twist mountain tunnel where both exits lead to the same door in the same house.

TWIST_MOUNTAIN_UPPER_TO_MIDDLE_Q <-> STRIATON_HOUSE_W_EXIT
TWIST_MOUNTAIN_UPPER_CAVE_Q_EXIT <-> STRIATON_HOUSE_W_EXIT

**Comment by adrienntindall** [comment]
Which season? Twist Mountain warps will be different depending on the season so I must've accidentally told the logic to randomize some twist mountain warps twice

**Comment by bsqrdminus4ac** [comment]
Spring

**Comment by adrienntindall** [comment]
Hmmm nothing seems wrong with the data files.. do you mind sending me the seed/randomizer version so I can see if it's an issue with the code?

**Comment by bsqrdminus4ac** [comment]
[White 2.nds_map_randomized.log](https://github.com/adrienntindall/hgss-map-randomizer/files/9089181/White.2.nds_map_randomized.log)

Version 1.4.6

**Comment by adrienntindall** [comment]
Aight so it looks like I forgot to port 1 line of code from HGSS to B2W2 when fixing the 2->1 bug that basically fixed a clause that said "don't try to insert a warp if it leads to itself" bc that would obviously break things.
Just to let you know how niche this is: not only did you have to get a seed with a warp that led to itself, that warp _also_ had to be chosen randomly in the 5-10 times the randomizer chooses to insert warps.
Luckily all this happens before the completability check so you can safely finish the rest of your run if it happens again before I push the next release.
