### ISSUE TITLE
Driftveil gym inaccessible

### ISSUE THREAD

**Issue by bsqrdminus4ac** [adrienntindall/hgss-map-randomizer#54]
Driftveil gym was randomized to the PWT entrance to relic passage.  However, the PWT main entrance was only accessible from route 9 east exit, and there was no way to reach route 9.  The route 9 mall lead to route 11, which only connected to the virbank complex dead end and a house interior.  The route 9 west exit went to MISTRALTON_CAVE_CLAY_TUNNEL_ENT, which is blocked off by a veteran (I believe until you beat the game).

Same log file from the twist mountain issue

**Comment by adrienntindall** [comment]
The veteran is the issue, he should've been removed but it looks like either that file didn't save properly or I forgot to transfer it over from the editor I was using to modify the maps. Logic should be functioning properly once that gets fixed
