### ISSUE TITLE
Iris' very weird team

### ISSUE THREAD

**Issue by Twengdi** [adrienntindall/hgss-map-randomizer#55]
I'm honestly not really sure if this is a bug, but Iris has a very weird team. Her team consisted of Klinklang, Typhlosion, Drapion, Altaria, Leafeon, and Gastrodon. Her team's levels were in the low 80s, except for Altaria which was level 90 (these levels are higher than even her challenge mode team). Is this team intentional?
[White 2 Random Map 1.log](https://github.com/adrienntindall/hgss-map-randomizer/files/9109028/White.2.Random.Map.1.log)

**Comment by adrienntindall** [comment]
aaaaaa this is supposed to be part of a surprise for some streamers later on- I'll delete this issue after an hour so you'll see this but it was not supposed to make it into the public test
