### ISSUE TITLE
Virbank gym inaccessible

### ISSUE THREAD

**Issue by bsqrdminus4ac** [adrienntindall/hgss-map-randomizer#58]
In this seed, Virbank Gym Interior was on Route 9, but every other entry point to Route 9 was a dead end.
Mall entrance was a dead end and the west exit led to a 3-way B2 reversal room.  One of the warps in that room was a dead end, and the other lead to the SE door in the twist mountain room with 6 doors.  The SE door is only accessible from the N and NE doors, but both of those led to dead ends.

Randomizer version 1.4.7 (Spring)
[Virbank inaccessible.log](https://github.com/adrienntindall/hgss-map-randomizer/files/9125115/Virbank.inaccessible.log)
,

**Comment by adrienntindall** [comment]
Looks like I swapped that northern warp with the northwestern warp in my Twist Mountain logic, so it thought you were able to get there from Chargestone Cave. My bad there, and thank you for brining it to my attention!
