### ISSUE TITLE
Iris located behind inaccessible room in Castelia Sewers

### ISSUE THREAD

**Issue by Twengdi** [adrienntindall/hgss-map-randomizer#62]
I decided to try playing on the game on Winter instead of Summer and found that Iris is located behind the left room in Castelia Sewers, which is the one room that is completely inaccessible when it is dry (during Autumn/Winter).
[White 2 Random Map 2.log](https://github.com/adrienntindall/hgss-map-randomizer/files/9185809/White.2.Random.Map.2.log)

**Comment by adrienntindall** [comment]
This issue is known and has been addressed but not pushed to the release yet as Ive been busy with other things. Just pushed the source code if you want the fixes sooner though, just need to replace whatever is in the files/ folder
