### ISSUE TITLE
Caitlin locked behind door in Abyssal Ruins

### ISSUE THREAD

**Issue by Twengdi** [adrienntindall/hgss-map-randomizer#63]
Caitlin is located behind a door in the Abyssal Ruins (dive puzzle), but afaik you can't actually move around this area in the randomizer.
[White 2 Random Map 1.log](https://github.com/adrienntindall/hgss-map-randomizer/files/9229770/White.2.Random.Map.1.log)

**Comment by adrienntindall** [comment]
You can move around the area, you just need to have the surf HM to do it (all tiles in there are considered water tiles, so just hit A with a mon with surf in your party)
