### ISSUE TITLE
Unbeatable seed - cianwood pharmacy trigger

### ISSUE THREAD

**Issue by DerianHaas** [adrienntindall/hgss-map-randomizer#7]
Had a seed where CIANWOOD_HOUSE_5_EXIT (Pharmacy interior) connected to CLIFF_GATE_INT_R47, which is blocked by workers until you get a call from Baoba about the safari zone.  However, the trigger for that call is saving the sick Ampharos, which you cannot do without accessing the pharmacy.

This seed also made surf unobtainable - ECRUTEAK_THEATER_EXIT connected to MT_MORTAR_LOWER_LADDER_UP_NW.  That ladder is only accessible from MT_MORTAR_LOWER_LADDER_DOWN, which connects to DARK_CAVE_S_TO_N, a section of Dark Cave blocked off by surfing.

[Attached log file](https://github.com/adrienntindall/hgss-map-randomizer/files/8694077/Soulsilver.unbeatable.randomized.log)

**Comment by adrienntindall** [comment]
Ah, I was not aware that that was the trigger for the Baoba call, thank you for the information.
It also looks like I completely forgot to include the flags in that section of dark cave completely, thank you for bringing it to my attention. Both issues will be addressed in the next patch later today/tomorrow
