### ISSUE TITLE
ROM does not load on a physical card

### ISSUE THREAD

**Issue by nathanfallet** [adrienntindall/hgss-map-randomizer#80]
After porting the randomizer to Linux (#79), I got a ROM of Heartgold randomized.
I played for a few hours on the emulator, and wanted to copy the ROM (and save) on my R4 to play later outside. But when I try to start the ROM from the R4, I get a white screen. The original ROM (I put in `heartgold_rom`) launches correctly though, and is able to read my save file.

My seed is `1446034678` (but not sure it changes anything), and I uploaded the original ROM I used [here](https://home.nathanfallet.me/PokemonHeartGoldFR.nds).

**Comment by adrienntindall** [comment]
Im unsure how to fix this as I don't have a way to put the rom on a physical card

**Comment by nathanfallet** [comment]
Update: tried on a friend's TTDS with the same file, and it works. I think the problem came from the cartridge I used the first time.
