### ISSUE TITLE
HGSS Radio Tower F1 Inaccessible

### ISSUE THREAD

**Issue by Tobulex** [adrienntindall/hgss-map-randomizer#81]
[Solo_add_map_2.nds_map_randomized.log](https://github.com/adrienntindall/hgss-map-randomizer/files/11355207/Solo_add_map_2.nds_map_randomized.log)
While attempting to complete this seed, radio tower F1 proved to be inaccessible. Its two exits eventually lead to either a dead end (The inner part of the Alph house), or to route 6 underground passage which cannot be opened until the Power plant event has been resolved. Making Whitney unable to be defeated because we can't get the radio card.

**Comment by adrienntindall** [comment]
You don't need the radio card to beat Whitney, that event just unblocks her gym
