### ISSUE TITLE
Impossible seed (?) Pokémon Soul Silver

### ISSUE THREAD

**Issue by Bartu25** [adrienntindall/hgss-map-randomizer#89]
Hello,

I don't know if anyone can help me, but I have been playing a SoulSilver map randomizer (trying to beat it in the intended order) and I think the seed is impossible. I have been doing good finding everything but Cianwood Gym, and after quite a time I just gave up and looked the log. It says:
**LIGHTHOUSE_EXTERIOR_ENT <-> CIANWOOD_GYM_EXIT**

Am I wrong or there is no way to access that door on the lighthouse exterior? Maybe I'm missing something or it isn't the door I think it is, but I checked everything I could to this point..
I did fix the power plant, I did not beat Team Rocket in the Radio Tower (but I found the director and he is in his room, I don't know if that's normal because I haven't played the game in a long time). Edit: I think TR doesn't take the Radio Tower until you get 7th badge if the info I found is correct.
I don't know, probably I just messed something, but in case someone can help me understanding the log better, it would be much appreciated.

[PKMN SS Map Randomizer 1.log](https://github.com/adrienntindall/hgss-map-randomizer/files/13326974/PKMN.SS.Map.Randomizer.1.log)

**Comment by adrienntindall** [comment]
The logs say try a house in Cherrygrove that takes you to Bell Tower, that should eventually take you to the lighthouse where there's a window where you jump down to the Cianwood Gym

**Comment by Bartu25** [comment]
OMG I DIDN'T EVEN KNOW THAT WAS A THING. I'm so dumb. Thank you for taking time to answer me =)
