### ISSUE TITLE
Unsure of how to set up randomization

### ISSUE THREAD

**Issue by DamiStorm** [adrienntindall/hgss-map-randomizer#9]
For the \heartgold_rom and \soulsilver_rom folders, do we have to make those folders (with the rom(s) we want to randomize within ofc) and place them into the folder? I can't seem to find those folders and when I try to make them with the roms inside and set them inside the same folder as the .exe, nothing works.

**Comment by adrienntindall** [comment]
The hgss-map-randomizer.zip has the environment set up for you, it sounds like you downloaded the source code.
You can find the latest release here:
https://github.com/adrienntindall/hgss-map-randomizer/releases/tag/Release
