### ISSUE TITLE
Abyssal Ruins impossible to traverse

### ISSUE THREAD

**Issue by awsmrs** [adrienntindall/hgss-map-randomizer#95]
I doubt this is gonna be seen and/or fixed cause of age, but the Abyssal Ruins is counted in logic even though it is impossible to traverse (most times when a warp takes you to Abyssal Ruins, you are placed in a walking state instead of a diving state, so you cannot move as there are invisible walls blocking your way) and I have encountered multiple seeds that have a gym only accessible from Abyssal Ruins. The only fix is to find a seed where one of the Abyssal Ruins warps is located in one of the four dive entrances, of which dive is still required to access anyway, so the then point is pretty moot.

**Comment by adrienntindall** [comment]
Abyssal ruins is traversable, you just need to have surf (and then use it while in the ruins)
